services:
  - type: web
    name: medicicol-api
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    region: ohio
    envVars:
      - key: DB_SERVER
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DRIVER
        value: "ODBC Driver 18 for SQL Server"
